import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const pages = JSON.parse(readFileSync(resolve(root, 'resources/seo/pages.json'), 'utf8'));
const check = process.argv.includes('--check');
const escape = (value) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const cloud = 'https://www.fokuscloud.com.br/';
const styles = 'https://styles.fokuscloud.com.br/';
const organization = { '@type': 'Organization', '@id': `${cloud}#organization`, name: 'Fokus Cloud', alternateName: 'FokusCloud', url: cloud };
const software = {
  '@type': 'SoftwareSourceCode', '@id': `${styles}#software`, name: 'Fokus Styles', url: styles,
  description: 'Framework CSS gratuito com licença MIT, tokens, temas e interações em JavaScript vanilla.',
  codeRepository: 'https://github.com/jorgewreis/fokus-styles',
  programmingLanguage: ['CSS', 'JavaScript'], license: 'https://opensource.org/licenses/MIT',
  sameAs: ['https://www.npmjs.com/package/fokus-styles'],
  isPartOf: { '@id': `${cloud}#website` },
};
let failures = 0;
for (const page of pages) {
  const path = resolve(root, 'public', page.file);
  const original = readFileSync(path, 'utf8');
  const siteUrl = `${new URL(page.url).origin}/`;
  const graph = [organization,
    { '@type': 'WebSite', '@id': `${siteUrl}#website`, url: siteUrl, name: page.site, inLanguage: 'pt-BR', publisher: { '@id': organization['@id'] } },
    { '@type': page.type, '@id': `${page.url}#webpage`, url: page.url, name: page.title, headline: page.title, description: page.description, inLanguage: 'pt-BR', isPartOf: { '@id': `${siteUrl}#website` }, about: { '@id': page.site === 'Fokus Styles' || page.url.endsWith('/fokus-styles') ? software['@id'] : organization['@id'] } },
  ];
  if (page.site === 'Fokus Styles' || page.url.endsWith('/fokus-styles')) graph.push(software);
  if (page.url !== siteUrl) {
    const crumbs = [{ '@type': 'ListItem', position: 1, name: page.site, item: siteUrl }];
    if (page.url.endsWith('/fokus-styles')) crumbs.push({ '@type': 'ListItem', position: 2, name: 'Produtos', item: `${cloud}produtos` });
    crumbs.push({ '@type': 'ListItem', position: crumbs.length + 1, name: page.title.split(' | ')[0], item: page.url });
    graph.push({ '@type': 'BreadcrumbList', '@id': `${page.url}#breadcrumb`, itemListElement: crumbs });
    graph[2].breadcrumb = { '@id': `${page.url}#breadcrumb` };
  }
  const metadata = `<!-- SEO: generated by npm run seo:sync; edit resources/seo/pages.json -->
        <title>${escape(page.title)}</title>
        <meta name="description" content="${escape(page.description)}" />
        <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta name="application-name" content="${page.site}" />
        <link rel="canonical" href="${page.url}" />
        <meta property="og:type" content="${page.type === 'TechArticle' ? 'article' : 'website'}" />
        <meta property="og:locale" content="pt_BR" />
        <meta property="og:site_name" content="${page.site}" />
        <meta property="og:title" content="${escape(page.title)}" />
        <meta property="og:description" content="${escape(page.description)}" />
        <meta property="og:url" content="${page.url}" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="${escape(page.title)}" />
        <meta name="twitter:description" content="${escape(page.description)}" />
        <script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2)}</script>
        <!-- /SEO -->`;
  let updated;
  if (original.includes('<!-- SEO:')) {
    updated = original.replace(/<!-- SEO:[\s\S]*?<!-- \/SEO -->/, metadata);
  } else {
    updated = original.replace(/\s*<title>[\s\S]*?<\/title>/gi, '')
      .replace(/\s*<meta\s+(?:name="(?:description|robots|googlebot|bingbot|application-name|twitter:[^"]+)"|property="og:[^"]+")[\s\S]*?\/>/gi, '')
      .replace(/\s*<link rel="canonical"[^>]+>/gi, '')
      .replace(/\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/gi, '')
      .replace(/<\/head>/i, `    ${metadata}\n    </head>`);
  }
  if (check && updated !== original) { console.error(`Outdated SEO metadata: ${page.file}`); failures++; }
  else if (!check && updated !== original) writeFileSync(path, updated);
}
if (failures) process.exitCode = 1;
else console.log(`${check ? 'Checked' : 'Synchronized'} SEO metadata for ${pages.length} public pages.`);
